before_script:
  - gem install hoe
  - gem install rake-compiler
  - gem install mini_portile
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
env:
  - USE_MINI_PORTILE=true
  - USE_MINI_PORTILE=false
notifications:
  email:
    - aaron@tenderlovemaking.com
    - luislavena@gmail.com
